[WIP] feat: Data.Fin.Lemmas <- mathlib
leanprover/std4 pull request #173
Opened 2023-07-02 06:10 UTC by digama0

A WIP branch for porting Mathlib.Data.Fin.Basic to std.

2023-07-04 20:36 UTC, fgdorais commented
What kind of assistance do you require?

2023-07-04 21:48 UTC, digama0 commented
It's basically unfinished work, I made it about 1/4 of the way through the file. The task here is to remove anything referencing mathlib notions like `NeZero` or `Equiv` and otherwise de-mathlibify all the other lemmas in the file. I haven't looked too carefully at the tail end of the file, maybe there is something that shouldn't be translated, but I would expect roughly the whole thing can move to std. This is relatively high priority since the mathlib std4 bump is blocked on this (in part).

2023-07-05 12:45 UTC, fgdorais requested changes
Custom recursors work better when the hypotheses have predictable and meaningful names. This is to facilitate the use of the pattern `induction x using foo with | hyp ... => ...` I went through and recommended better names.

PS: Also consider using `motive` instead of `C` but I don't think that's essential.

2023-07-05 12:45 UTC, fgdorais commented on Std/Data/Fin/Lemmas.lean
> +@[elab_as_elim] def succRec {C : ∀ n, Fin n → Sort _} (H0 : ∀ n, C n.succ (0 : Fin (n + 1)))
Hypotheses: `H0` -> `zero`, `Hs` -> `succ`

2023-07-05 12:45 UTC, fgdorais commented on Std/Data/Fin/Lemmas.lean
> +@[elab_as_elim] def succRecOn {n : Nat} (i : Fin n) {C : ∀ n, Fin n → Sort _}
Hypotheses: `H0` -> `zero`, `Hs` -> `succ`

2023-07-05 12:45 UTC, fgdorais commented on Std/Data/Fin/Lemmas.lean
> +@[elab_as_elim] def induction {C : Fin (n + 1) → Sort _} (h0 : C 0)
Hypotheses: `h0` -> `zero`, `hs` -> `succ`

2023-07-05 12:45 UTC, fgdorais commented on Std/Data/Fin/Lemmas.lean
> +@[elab_as_elim] def inductionOn (i : Fin (n + 1)) {C : Fin (n + 1) → Sort _} (h0 : C 0)
Hypotheses: `h0` -> `zero`, `hs` -> `succ`

2023-07-05 12:45 UTC, fgdorais commented on Std/Data/Fin/Lemmas.lean
> +@[elab_as_elim] def cases {C : Fin (n + 1) → Sort _} (H0 : C 0) (Hs : ∀ i : Fin n, C i.succ) :
Hypotheses: `H0` -> `zero`, `Hs` -> `succ`

2023-07-05 12:45 UTC, fgdorais commented on Std/Data/Fin/Lemmas.lean
> +@[elab_as_elim] def reverseInduction {C : Fin (n + 1) → Sort _} (hlast : C (Fin.last n))
Hypotheses: `hlast` -> `last`, `hs` -> `cast`

2023-07-05 12:45 UTC, fgdorais commented on Std/Data/Fin/Lemmas.lean
> +@[elab_as_elim] def lastCases {n : Nat} {C : Fin (n + 1) → Sort _} (hlast : C (Fin.last n))
Hypotheses: `hlast` -> `last`, `hcast` -> `cast`

2023-07-05 12:45 UTC, fgdorais commented on Std/Data/Fin/Lemmas.lean
> +@[elab_as_elim] def addCases {m n : Nat} {C : Fin (m + n) → Sort u} (hleft : ∀ i, C (castAdd n i))
Hypotheses: `hleft` -> `left`, `hright` -> `right`

2023-07-05 12:49 UTC, kmill commented
The de-ord-embedding/iso-ification seems like it was done right, so here's a :+1: from me, though I only checked about 400-500 lines in detail

2023-07-06 04:03 UTC, fgdorais approved these changes

2023-07-06 06:33 UTC, merged