fix: rename Nat.coprime to Nat.Coprime
leanprover/std4 pull request #187
Opened 2023-07-19 14:27 UTC by eric-wieser

It's a prop, so should be PascalCase.

2023-07-19 20:30 UTC, fgdorais requested changes

2023-08-20 14:06 UTC, fgdorais requested changes

2023-08-20 14:06 UTC, fgdorais commented on Std/Data/Nat/Gcd.lean
>      rw [coprime, Nat.gcd_assoc, H.symm.gcd_eq_one, gcd_one_right]
```suggestion
    rw [Coprime, Nat.gcd_assoc, H.symm.gcd_eq_one, gcd_one_right]
```

2023-08-20 14:06 UTC, fgdorais commented on Std/Data/Nat/Gcd.lean
>    rw [coprime] at H2
```suggestion
  rw [Coprime] at H2
```

2023-08-20 17:28 UTC, fgdorais approved these changes

2023-08-20 17:33 UTC, fgdorais requested changes
Just a few more.

2023-08-20 17:33 UTC, fgdorais commented on Std/Data/Nat/Gcd.lean
> +@[simp] theorem coprime_zero_right (n : Nat) : Coprime n 0 ↔ n = 1 := by simp [coprime]
```suggestion
@[simp] theorem coprime_zero_right (n : Nat) : Coprime n 0 ↔ n = 1 := by simp [Coprime]
```

2023-08-20 17:33 UTC, fgdorais commented on Std/Data/Nat/Gcd.lean
> +@[simp] theorem coprime_zero_left (n : Nat) : Coprime 0 n ↔ n = 1 := by simp [coprime]
```suggestion
@[simp] theorem coprime_zero_left (n : Nat) : Coprime 0 n ↔ n = 1 := by simp [Coprime]
```

2023-08-20 17:33 UTC, fgdorais commented on Std/Data/Nat/Gcd.lean
> +@[simp] theorem coprime_self (n : Nat) : Coprime n n ↔ n = 1 := by simp [coprime]
```suggestion
@[simp] theorem coprime_self (n : Nat) : Coprime n n ↔ n = 1 := by simp [Coprime]
```

2023-09-14 23:03 UTC, eric-wieser commented
@fgdorais: this now builds

2023-09-14 23:14 UTC, merged