feat: add the json% macro from ProofWidgets4
leanprover/std4 pull request #267
Opened 2023-09-19 18:28 UTC by PatrickMassot

---

See Zulip discussion at https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/json.20elaborator

2023-09-19 18:37 UTC, digama0 requested changes
Comments/concerns:
* It should be in `Std` not `ProofWidgets`
* The instances at the start are misplaced, and should go in `Std.Lean` or in lean itself
* The syntax should not be scoped, and if this causes problems we need to fix those before merge (mathlib bump test needed)
* The `$(` token conflicts with lean antiquotations

2023-09-20 00:44 UTC, PatrickMassot commented
Do you have a suggestion to replace `$(`?

2023-09-20 00:45 UTC, digama0 commented
ideally it would be `$(`, but some research is needed to determine how to do this without messing up other uses of antiquotations. Perhaps the implementation in Qq could be helpful...

2023-09-20 00:55 UTC, PatrickMassot commented
I made the easy changes but the quotation thing may be above my pay grade.

2023-09-20 01:53 UTC, PatrickMassot commented
@gebner do you have any insight about reusing the antiquotation syntax coming from Qq?

2023-09-20 05:08 UTC, sgouezel commented on Std/Data/Json.lean
> +open scoped ProofWidgets.Json
```suggestion
open scoped Std.Json
```

2023-09-22 19:37 UTC, Vtec234 commented
Hello, I improved the antiquotation story [here](https://github.com/EdAyers/ProofWidgets4/commit/9f68f14df384f43b74aeb2908b97ae54a0ad9d95). Feel free to update the PR with those changes. I kept the PW4 variant `scoped` because even with the changes I am not confident that it won't break global syntax. Probably if you remove `scoped` here and both std4/mathlib4 still compile, then it's ok.

2023-09-22 22:07 UTC, gebner commented
> do you have any insight about reusing the antiquotation syntax coming from Qq?

Qq uses the same quotation syntax as Lean core.  Wojciech has now changed the json macro in proofwidgets to do the same. ^^

2023-10-04 22:40 UTC, PatrickMassot commented
I tried to incorporate changes from ProofWidgets.

2023-10-04 23:24 UTC, Vtec234 approved these changes

2023-10-04 23:24 UTC, Vtec234 commented on Std/Data/Json.lean
> +declare_syntax_cat jso_ident
```suggestion
```

2023-10-04 23:24 UTC, Vtec234 commented on Std/Data/Json.lean
> +/-- Json dictionary syntax. -/
```suggestion
/-- Json object syntax. -/
```

2023-10-04 23:24 UTC, Vtec234 commented on Std/Data/Json.lean
> +/-- Json data syntax. -/
```suggestion
/-- Json syntactic category -/
```

2023-10-09 22:38 UTC, Vtec234 commented
@digama0 this is good to go I think.

2023-10-09 23:00 UTC, digama0 commented on Std/Lean/Json.lean
> +      Json.num j
This instance looks super hackish, translating stuff to strings and then back, and constructing invalid JSON literals like `nan`. What is going on here? (If you want to translate invalid floats I think the usual method is to use `null` instead.)

2023-10-23 22:26 UTC, digama0 approved these changes

2023-10-23 22:27 UTC, merged