feat(Rat/Lemmas): add `mk_den_one`; golf
leanprover/std4 pull request #617
Opened 2024-02-11 11:56 UTC by adomani

This PR extracts the new lemma `mk_den_one`, previously introduced in #611 and uses it to golf some proofs.

2024-02-11 22:48 UTC, fgdorais requested changes
This can be made independent of #611.

2024-02-11 22:48 UTC, fgdorais commented on Std/Data/Rat/Basic.lean
> +structure Rat where
Restore to original state to avoid dependency on #611 .
```suggestion
@[ext] structure Rat where
```

2024-02-11 22:48 UTC, fgdorais commented on Std/Data/Rat/Lemmas.lean
> +attribute [local ext] Rat
Remove to avoid dependency on #611.

2024-02-11 22:48 UTC, fgdorais commented on Std/Data/Rat/Lemmas.lean
> +@[simp] theorem mk_den_one {r : Int} :
Excellent simp lemma! The name is still unusual but there are probably no uses outside simp, so it doesn't matter much.

2024-02-12 01:20 UTC, adomani commented
@fgdorais thanks for the suggestions!  I made this PR independent on the one with `Rat.ext`.

2024-02-12 11:20 UTC, fgdorais approved these changes

2024-02-13 05:22 UTC, joehendrix approved these changes
The seems sensible to me.

2024-02-15 05:58 UTC, merged