feat: Function.funext_iff and Sum.elim_eq_iff
leanprover/std4 pull request #715
Opened 2024-03-26 13:38 UTC by madvorak

I didn't really know where to put `Function.funext_iff` because `Std/Data/Sum/Lemmas` imports `Std/Data/Sum/Basic` and nothing else. Please refactor!

2024-03-26 13:41 UTC, madvorak commented
awaiting-review

2024-03-26 22:36 UTC, semorrison commented on Std/Data/Sum/Lemmas.lean
> +theorem Function.funext_iff {β : α → _} {f₁ f₂ : ∀ x : α, β x} : f₁ = f₂ ↔ ∀ a, f₁ a = f₂ a :=
```suggestion
theorem Function.funext_iff {β : α → Sort u} {f₁ f₂ : ∀ x : α, β x} : f₁ = f₂ ↔ ∀ a, f₁ a = f₂ a :=
```

2024-03-26 22:36 UTC, semorrison commented on Std/Data/Sum/Lemmas.lean
> +theorem Function.funext_iff {β : α → _} {f₁ f₂ : ∀ x : α, β x} : f₁ = f₂ ↔ ∀ a, f₁ a = f₂ a :=
Please move to `Std.Logic`, after `funext₃`.

2024-03-27 07:56 UTC, madvorak commented
I get this error:
```
[109/165] Building Std.Dataerror: > c:\Users\mdvorak\.elan\toolchains\leanprover--lean4---v4.7.0-rc2\bin\leanc.exe -o .\.lake\build\bin\runLinter.exe .\.lake\build\ir\runLinter.c.o .\.lake\build\ir\Std\Tactic\Lint\Basic.c.o .\.lake\build\ir\Std\Tactic\Lint\Misc.c.o .\.lake\build\ir\Std\Tactic\OpenPrivate.c.o .\.lake\build\ir\Std\Util\LibraryNote.c.o .\.lake\build\ir\Std\Tactic\Lint\Simp.c.o .\.lake\build\ir\Std\Tactic\Lint\TypeClass.c.o .\.lake\build\ir\Std\Tactic\Lint\Frontend.c.o .\.lake\build\ir\Std\Tactic\Lint.c.o .\.lake\build\ir\Std\Data\List\Init\Attach.c.o .\.lake\build\ir\Std\Data\Array\Basic.c.o .\.lake\build\ir\Std\Lean\Util\Path.c.o
error: stderr:
ld.lld: error: too many exported symbols (got 65747, max 65535)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: external command `c:\Users\mdvorak\.elan\toolchains\leanprover--lean4---v4.7.0-rc2\bin\leanc.exe` exited with code 1
```

2024-03-27 07:57 UTC, madvorak commented
awaiting-review

2024-04-01 09:52 UTC, fgdorais requested changes

2024-04-01 09:52 UTC, fgdorais commented on Std/Logic.lean
> +  Iff.intro (fun hf _ => hf ▸ rfl) funext
```suggestion
  ⟨congr_fun, funext⟩
```

2024-04-03 15:43 UTC, fgdorais approved these changes

2024-04-17 04:24 UTC, merged